name: 'Snyk SBOM Wrapper'
description: 'A wrapper for Snyk to simplify SBOM generation'
inputs:
  scan_directory:
    description: 'Directory to scan project files in (default to all projects if not specified)'
    type: string
    default: '--all-projects'
  exclude:
    description: 'directory and/or file name(s) to exclude from the scan, must comma-separated if multiple files/directories are provided. Only works with SCA scan type'
    type: string
    default: ''
  sbom_name:
    description: 'Name you want the sbom to have'
    required: true
    type: string
    default: 'snyk_sbom'
  token:
    description: 'Snyk auth token'
    required: true
    type: string
    secret: true
runs:
  using: 'composite'
  steps:
    - name: Set global vars
      id: vars
      shell: bash
      run: |
        # Extract base filename without extension if present
        FILENAME="${{ inputs.sbom_name }}"
        if [[ "$FILENAME" != *.json ]]; then
          FILENAME="${FILENAME}.json"
        fi
        echo "snyk_output_sbom=$FILENAME" >> "${GITHUB_OUTPUT}"
    - name: Setup Snyk
      uses: actions/snyk/setup@CLI-383-update-git-hub-actions-readme
    - name: setup node
      uses: actions/setup-node@v3.8.1
      with:
        node-version: latest

    - name: Run Snyk SBOM generation
      id: scan
      shell: bash
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ inputs.token }}
      run: |
        : # do not exit on error
        set +e
        
        : # validate scan_directory variable
        if [ "${{ inputs.scan_directory }}" == "" ]; then
          DIRS_TO_SCAN='--all-projects'
          echo "dirs_to_scan=--all-projects" >> "${GITHUB_OUTPUT}"
        elif [ "${{ inputs.scan_directory }}" == " " ]; then
          DIRS_TO_SCAN='--all-projects'
        else
          DIRS_TO_SCAN="${{ inputs.scan_directory }}"
        fi

        : # assign/validate snyk cli command based on scan_type provided
        if [ "${{ inputs.exclude }}" != "" ]; then
          EXCLUSION="--exclude=${{ inputs.exclude }}"
        else
          EXCLUSION="${{ inputs.exclude }}"
        fi 
        echo "scan_dirs=$DIRS_TO_SCAN" >> "${GITHUB_OUTPUT}"
        
        start_time=$(date +%s)
        
        : # run snyk scan
        snyk sbom "$DIRS_TO_SCAN" "$EXCLUSION" --format=cyclonedx1.5+json --json-file-output="${{ steps.vars.outputs.snyk_output_sbom }}"
        
        end_time=$(date +%s)
        runtime=$((end_time - start_time))
        runtime_minutes=$((runtime / 60))

    - name: Upload code sbom content
      if: always()
      uses: actions/upload-artifact@v3.1.3
      with:
        path: |
          ${{ steps.vars.outputs.snyk_output_sbom }}
