name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: .   #default is the root of the repository
          REQUIREMENT_PATH: requirements.txt  #default is requirement.txt in the root of your repository 
      - name: Commit requirements.txt (if changed)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add PandasGUI/requirements.txt
          git commit -m "Auto-generate requirements.txt" || echo "No changes to commit"
          git push
