name: Main Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run standardized build
        uses: ./actions/build   # <— this points to actions/build/action.yml
        with:
          language: node
          version: 18
          build-directory: ./src
