name: Main Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  snyk-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sbom-generator
        with:
          org: my-snyk-org
          token: ${{ secrets.SNYK_TOKEN }}

