name: Main Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    uses: ../actions/build   # path to the Snyk reusable workflow
    with:
      org: my-snyk-org
      scan_type: SOURCE_CODE
      scan_directory: ./src
      exclude_folders: node_modules,dist
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}
