name: Generate SBOM

on: [push]

jobs:
  generate_sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: manifest-cyber/manifest-github-action@v1
        with:
          action: generate
          generator: syft
          format: cyclonedx
          output-file: sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact
          path: sbom.json
