    name: Generate Build Manifest

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: onebeyond/make-manifest@v1
            with:
              output-file: build-manifest.json
          - name: Upload manifest
            uses: actions/upload-artifact@v4
            with:
              name: build-manifest
              path: build-manifest.json
