name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: requirements.txt
      - name: Upload requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: requirements.txt
          path: requirements.txt

  sbom:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download requirements.txt from build job
        uses: actions/download-artifact@v4
        with:
          name: requirements.txt
          path: ./
      - name: Show requirements.txt contents
        run: cat requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Snyk
        run: npm install -g snyk
      - name: Generate SBOM using Snyk
        id: scan
        shell: bash
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.token }}
        run: |
          : # Run Auth
          snyk auth ${{secrets.SNYK_TOKEN}}
          : # Generate SBOM
          snyk sbom --file=requirements.txt --format=cyclonedx1.5+json > sbom.json

